# Generated by Django 3.1.7 on 2021-03-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='locality',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='state',
            new_name='province',
        ),
    ]
