# Generated by Django 3.1.7 on 2021-04-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
