# Generated by Django 3.1.7 on 2021-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_orderplaced_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(),
        ),
    ]
