# Generated by Django 3.1.7 on 2021-04-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210413_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='more_images',
            new_name='images',
        ),
    ]
