# Generated by Django 3.1.7 on 2021-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='productimg/images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
