# Generated by Django 3.1.7 on 2021-04-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210413_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='more_images',
        ),
    ]
