# Generated by Django 3.1.7 on 2021-04-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210413_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageb',
            field=models.ImageField(null=True, upload_to='productimg/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagels',
            field=models.ImageField(null=True, upload_to='productimg/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagers',
            field=models.ImageField(null=True, upload_to='productimg/images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
