# Generated by Django 3.1.7 on 2021-04-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210414_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageb',
            field=models.ImageField(upload_to='productimg/images'),
        ),
    ]
