# Generated by Django 3.1.7 on 2021-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_product_imageb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='media/static/uploads/rog.jpg', upload_to='static/uploads'),
        ),
    ]
