# Generated by Django 3.1.7 on 2021-04-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210416_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/uploads/rog.png', upload_to='static/uploads'),
        ),
    ]
