# Generated by Django 3.1.7 on 2021-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210416_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.IntegerField(null=True),
        ),
    ]
